obstacles:
  #- name: "Obstacle1"
  #  position: [0.25, 0.3, 0.8]
  #  velocity: [0.0, 0.0, 0.0]
  #  radius: 0.07
  #  is_dynamic: false
  #  angular_speed: 0.0
  #- name: "Obstacle2"
  #  position: [0.25, -0.3, 0.8]
  #  velocity: [0.0, 0.0, 0.0]
  #  radius: 0.07
  #  is_dynamic: false
  #  angular_speed: 0.0
  #- name: "Obstacle3"
  #  position: [0.5, 0.3, 0.6]
  #  velocity: [0.0, 0.0, 0.0]
  #  radius: 0.07
  #  is_dynamic: false
  #  angular_speed: 0.0
  #- name: "Obstacle4"
  #  position: [0.5, -0.3, 0.6]  
  #  velocity: [0.0, 0.0, 0.0]
  #  radius: 0.07
  #  is_dynamic: false
  #  angular_speed: 0.0
  - name: "Obstacle5"
    position: [0.25, -0.1, 0.3]
    velocity: [0.0, 0.0, 0.0]
    radius: 0.01
    is_dynamic: false
    angular_speed: 0.0